### ISSUE TITLE
Numeric formatting of variances not possible

### ISSUE THREAD

**Issue by matbmeijer** [AnalyticsEarth/variance-waterfall#1]
Hi, first of all thank you for your extension - it is a much needed functionality, and fulfills a great necessity. Just one detail - as of today it is not possible to format the digits of the variance measures. Would there be any way to do this?

Kind regards!

**Comment by patricnordstrom** [comment]
If you set the same number format for both measures you will get the same number format for the dimension variance bars.

https://betahelp.qlik.com/en-US/sense/September2019/Subsystems/Hub/Content/Sense_Hub/Visualizations/VisualizationBundle/variance-waterfall.htm

**Comment by matbmeijer** [comment]
Thank you @patricnordstrom , I am sorry! I did not see it!
